import { Router } from "express";
import adminSchoolRoutes from "./admin-school.routes";
import adminUserRoutes from "./admin-user.routes";
import authRoutes from "./auth.routes";
import categoryAdminRoutes from "./category-admin.routes";
import dashboardRoutes from "./dashboard.routes";
import miniAddressRoutes from "./mini-address.routes";
import miniFavoriteRoutes from "./mini-favorite.routes";
import messageAdminRoutes from "./message-admin.routes";
import merchantAuthRoutes from "./merchant-auth.routes";
import merchantRoutes from "./merchant.routes";
import merchantSupplyRoutes from "./merchant-supply.routes";
import miniMessageRoutes from "./mini-message.routes";
import miniMerchantRoutes from "./mini-merchant.routes";
import miniOrderRoutes from "./mini-order.routes";
import miniOperationRoutes from "./mini-operation.routes";
import miniPayRoutes from "./mini-pay.routes";
import miniPostRoutes from "./mini-post.routes";
import miniShopApplyRoutes from "./mini-shop-apply.routes";
import miniStoreRoutes from "./mini-store.routes";
import miniUploadRoutes from "./mini-upload.routes";
import miniWalletRoutes from "./mini-wallet.routes";
import operationAdminRoutes from "./operation-admin.routes";
import postAdminRoutes from "./post-admin.routes";
import productSpecRoutes from "./product-spec.routes";
import productAdminRoutes from "./product-admin.routes";
import schoolContentRoutes from "./school-content.routes";
import schoolAdminApplicationRoutes from "./school-admin-application.routes";
import statAdminRoutes from "./stat-admin.routes";
import systemRoutes from "./system.routes";
import tradeAdminRoutes from "./trade-admin.routes";
import travelRoutes from "./travel.routes";
import userPublishRoutes from "./user-publish.routes";
import verificationRoutes from "./verification.routes";
import wechatPayRoutes from "./wechat-pay.routes";

const router = Router();

router.use("/dashboard", dashboardRoutes);
router.use("/school/admin", adminSchoolRoutes);
router.use("/user/admin", adminUserRoutes);
router.use("/auth", authRoutes);
router.use("/category/admin", categoryAdminRoutes);
router.use("/message/admin", messageAdminRoutes);
router.use("/api/merchant/auth", merchantAuthRoutes);
router.use("/api/merchant", merchantRoutes);
router.use("/merchant/auth", merchantAuthRoutes);
router.use("/merchant/supply", merchantSupplyRoutes);
router.use("/merchant", merchantRoutes);
router.use("/operation", operationAdminRoutes);
router.use("/post/admin", postAdminRoutes);
router.use("/mini/address", miniAddressRoutes);
router.use("/mini/favorite", miniFavoriteRoutes);
router.use("/mini/message", miniMessageRoutes);
router.use("/mini/merchant", miniMerchantRoutes);
router.use("/mini/order", miniOrderRoutes);
router.use("/mini/operation", miniOperationRoutes);
router.use("/mini/pay", miniPayRoutes);
router.use("/mini/post", miniPostRoutes);
router.use("/shop/apply", miniShopApplyRoutes);
router.use("/mini/store", miniStoreRoutes);
router.use("/mini/upload", miniUploadRoutes);
router.use("/mini/wallet", miniWalletRoutes);
router.use("/verify", verificationRoutes);
router.use("/school/content", schoolContentRoutes);
router.use("/school-admin/apply", schoolAdminApplicationRoutes);
router.use("/user/publish", userPublishRoutes);
router.use("/product/spec", productSpecRoutes);
router.use("/product/admin", productAdminRoutes);
router.use("/stat/admin", statAdminRoutes);
router.use("/system", systemRoutes);
router.use("/trade/admin", tradeAdminRoutes);
router.use("/travel", travelRoutes);
router.use("/wechat/pay", wechatPayRoutes);

export default router;
